In [47]:
# Q1 
import numpy as n
x=n.array([0,1,2,3,4,5])
print(x.dtype)


int32


In [48]:
# Q2
x=n.array([1.0,2.0])
print(x.dtype=='float64')


True


In [49]:
# Q3
x=n.array([1+2j,2+3j,3+4j],dtype='complex128')
print(x)


[1.+2.j 2.+3.j 3.+4.j]


In [50]:
# Q4
x=n.array([1,2,3])
print(x.astype('float32'))


[1. 2. 3.]


In [51]:
# Q5
x=n.array([1.1,2.2,3.3],dtype='float64')
print(x.astype('float32'))


[1.1 2.2 3.3]


In [52]:
# Q6
def aa(x):
 return x.shape,x.size,x.dtype
x=n.array([1,2,3])
print(aa(x))


((3,), 3, dtype('int32'))


In [53]:
# Q7
def bb(x):
 return x.ndim
x=n.array([[1,2],[3,4]])
print(bb(x))


2


In [54]:
# Q8
def cc(x):
 return x.itemsize,x.nbytes
x=n.array([1,2,3])
print(cc(x))


(4, 12)


In [55]:
# Q9
def dd(x):
 return x.strides
x=n.array([[1,2],[3,4]])
print(dd(x))


(8, 4)


In [56]:
# Q10
def ee(x):
 return x.shape,x.strides
x=n.array([[1,2],[3,4]])
print(ee(x))


((2, 2), (8, 4))


In [57]:
# Q11
def zz(size):
    return n.zeros(size)

print(zz(5))



[0. 0. 0. 0. 0.]


In [58]:
# Q12
def oo(r,c):
 return n.ones((r,c))
print(oo(2,3))


[[1. 1. 1.]
 [1. 1. 1.]]


In [59]:
# Q13
def rr(s,e,t):
 return n.arange(s,e,t)
print(rr(1,10,2))


[1 3 5 7 9]


In [60]:
# Q14
def tt(a, b, num):
    return n.linspace(a, b, num)

print(tt(1, 2, 5))



[1.   1.25 1.5  1.75 2.  ]


In [61]:
# Q15

def mm(size):
    return n.eye(size)

print(mm(3))



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [62]:
# Q16
a=[1,2,3]
print(n.array(a))


[1 2 3]


In [63]:
# Q17
a=n.array([1,2,3])
b=a.view()
print(b)


[1 2 3]


In [64]:
# Q18
def cat(a,b,ax):
 return n.concatenate((a,b),axis=ax)
print(cat(n.array([[1,2]]),n.array([[3,4]]),0))


[[1 2]
 [3 4]]


In [65]:
# Q19
a=n.array([[1,2]])
b=n.array([[3],[4]])
print(n.concatenate((a,b.T),axis=1))


[[1 2 3 4]]


In [66]:
# Q20
a=[n.array([1,2]),n.array([3,4])]
print(n.vstack(a))


[[1 2]
 [3 4]]


In [67]:
# Q21
def p(a,b,s):
 return n.arange(a,b+1,s)
print(p(1,10,2))


[1 3 5 7 9]


In [68]:
# Q22
print(n.linspace(0,1,10))


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [69]:
# Q23
print(n.logspace(0,3,5))


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [70]:
# Q24
import pandas as p
a=n.random.randint(1,101,(5,3))
d=p.DataFrame(a)
print(d)


    0   1   2
0  90  10  56
1   7  95  60
2  28   5  91
3  99  20  80
4  62  11  82


In [71]:
# Q25
def q(d,col):
 d[col]=n.where(d[col]<0,0,d[col])
 return d
d=p.DataFrame({'a':[1,-2,3]})
print(q(d,'a'))


   a
0  1
1  0
2  3


In [72]:
# Q26
a=n.array([1,2,3,4])
print(a[2])


3


In [73]:
# Q27
a=n.array([[1,2,3],[4,5,6]])
print(a[1][2])


6


In [74]:
# Q28
a=n.array([1,6,8,3])
print(a[a>5])


[6 8]


In [75]:
# Q29
a=n.array([1,2,3,4,5,6])
print(a[2:6])


[3 4 5 6]


In [76]:
# Q30
a=n.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[[0,1],[1,2]])


[2 6]


In [77]:
# Q31
a=n.array([[1,2],[3,4]])
print(a[[0,1],[1,0]])


[2 3]


In [78]:
# Q32
a=n.array([1,4,7,10])
print(a[a>5])


[ 7 10]


In [79]:
# Q33
a=n.arange(27).reshape(3,3,3)
print(a[[0,1],[1,2],[2,0]])


[ 5 15]


In [80]:
# Q34
a=n.array([1,2,3,4,5])
print(a[(a>2)&(a<5)])


[3 4]


In [81]:
# Q35
a=n.array([[1,2,3],[4,5,6]])
print(a[[0,1],[2,0]])


[3 4]


In [82]:
# Q36
a=n.array([1,2,3])
print(a+5)


[6 7 8]


In [83]:
# Q37
a=n.ones((3,4))
b=n.array([[1],[2],[3]])
print(a*b)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [84]:
# Q38
a=n.ones((4,3))
b=n.ones((1,3))
print(a+b)


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [85]:
# Q39
a=n.ones((3,1))
b=n.ones((1,3))
print(a+b)


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [86]:
# Q40
a=n.ones((2,3))
b=n.ones((2,2))
try:
 print(a*b)
except:
 print('bad shape')


bad shape


In [87]:
# Q41
a=n.array([[1,2],[3,4]])
print(a.mean(axis=0))


[2. 3.]


In [88]:
# Q42
a=n.array([[1,5],[2,3]])
print(a.max(axis=1))


[5 3]


In [89]:
# Q43
a=n.array([[1,5],[2,3]])
print(a.argmax(axis=0))


[1 0]


In [90]:
# Q44
def f(x):
 return n.convolve(x,[1,1,1],'valid')
a=n.array([[1,2,3,4],[5,6,7,8]])
print([f(r) for r in a])


[array([6, 9]), array([18, 21])]


In [91]:
# Q45
a=n.array([[2,4],[6,8]])
print((a%2==0).all(axis=0))


[ True  True]


In [92]:
# Q46
a=n.arange(6)
print(a.reshape(2,3))


[[0 1 2]
 [3 4 5]]


In [93]:
# Q47
a=n.array([[1,2],[3,4]])
print(a.flatten())


[1 2 3 4]


In [94]:
# Q48
a=n.array([[1,2]])
b=n.array([[3,4]])
print(n.concatenate((a,b),axis=0))


[[1 2]
 [3 4]]


In [95]:
# Q49
a=n.array([1,2,3,4,5,6])
print(n.split(a,3))


[array([1, 2]), array([3, 4]), array([5, 6])]


In [96]:
# Q50
a=n.array([1,2,3])
a=n.insert(a,1,9)
a=n.delete(a,2)
print(a)


[1 9 3]


In [97]:
# Q51
a=n.array([1,2])
b=n.array([3,4])
print(a+b)


[4 6]


In [98]:
# Q52
a=n.array([5,6])
b=n.array([2,1])
print(a-b)


[3 5]


In [99]:
# Q53
a=n.array([1,2])
b=n.array([3,4])
print(a*b)


[3 8]


In [100]:
# Q54
a=n.array([6,8])
b=n.array([2,2])
print(a/b)


[3. 4.]


In [101]:
# Q55
a=n.array([2,3])
b=n.array([3,2])
print(a**b)


[8 9]


In [102]:
# Q56
a=n.array(['apple','banana','apple'])
print(n.char.count(a,'apple'))


[1 0 1]


In [103]:
# Q57
a=n.array(['HeLLo','WorLD'])
print([c for x in a for c in x if c.isupper()])


['H', 'L', 'L', 'W', 'L', 'D']


In [104]:
# Q58
a=n.array(['hi moon','moon is big'])
print(n.char.replace(a,'moon','sun'))


['hi sun' 'sun is big']


In [105]:
# Q59
a=n.array(['hi','bye'])
b=n.array(['1','2'])
print(n.char.add(a,b))


['hi1' 'bye2']


In [106]:
# Q60
a=n.array(['a','abc','hello'])
print(max([len(i) for i in a]))


5


In [107]:
# Q61
a=n.random.randint(1,1001,100)
print(n.mean(a),n.median(a),n.var(a),n.std(a))


549.33 564.0 75897.1011 275.4942850586923


In [108]:
# Q62
a=n.random.randint(1,101,50)
print(n.percentile(a,25),n.percentile(a,75))


31.5 75.0


In [109]:
# Q63
a=n.array([1,2,3])
b=n.array([4,5,6])
print(n.corrcoef(a,b))


[[1. 1.]
 [1. 1.]]


In [110]:
# Q64
a=n.array([[1,2],[3,4]])
b=n.array([[2,0],[1,2]])
print(n.dot(a,b))


[[ 4  4]
 [10  8]]


In [111]:
# Q65
a=n.random.randint(1,101,50)
print(n.percentile(a,[10,50,90]))


[16.9 48.5 89.3]


In [112]:
# Q66
a=n.array([5,10,15])
print(n.where(a==10))


(array([1], dtype=int64),)


In [113]:
# Q67
a=n.random.randint(1,100,10)
print(n.sort(a))


[ 8 19 19 20 51 57 69 69 69 71]


In [114]:
# Q68
a=n.array([10,25,30])
print(a[a>20])


[25 30]


In [115]:
# Q69
a=n.array([3,6,10,12])
print(a[a%3==0])


[ 3  6 12]


In [116]:
# Q70
a=n.array([10,25,35,45])
print(a[(a>=20)&(a<=40)])


[25 35]


In [119]:
# Q71
a=n.array([1,2,3])
print(a.dtype.byteorder)


=


In [118]:
# Q72
a=n.array([1,256],dtype='>i2')
a.byteswap(True)
print(a)


[256   1]
